"""empty message

Revision ID: 9202a9f5358e
Revises: 9a8a87cc4747
Create Date: 2020-10-29 08:21:23.802233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9202a9f5358e'
down_revision = '9a8a87cc4747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test_case', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case', type_='unique')
    # ### end Alembic commands ###
