"""empty message

Revision ID: 9a8a87cc4747
Revises: edf0c6666542
Create Date: 2020-10-29 07:47:23.214733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8a87cc4747'
down_revision = 'edf0c6666542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'name')
    # ### end Alembic commands ###
