"""empty message

Revision ID: 9ac0a7dd5dc8
Revises: 1d48c57d7c9e
Create Date: 2020-10-28 19:30:32.135900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac0a7dd5dc8'
down_revision = '1d48c57d7c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_run_timestamp'), 'test_run', ['timestamp'], unique=False)
    op.drop_index('ix_test_runs_timestamp', table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('result', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_runs_timestamp', 'test_runs', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_test_run_timestamp'), table_name='test_run')
    op.drop_table('test_run')
    # ### end Alembic commands ###
