"""empty message

Revision ID: edf0c6666542
Revises: 627a90755a5c
Create Date: 2020-10-29 07:46:39.419685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf0c6666542'
down_revision = '627a90755a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('number', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
